#! /bin/sh


##autostaaart

sxhkd &
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale ~/.config/wallpapers/godlike.jpg
#${HOME}/.config/polybar/launch.sh --forest&
$HOME/.config/polybar/forest/launch.sh
. "${HOME}/.cache/wal/colors.sh"


###Monitors###

bspc monitor -d 0 1 2 3 4 5 6

####BSPWM configs#######


bspc config border_width        2 
bspc config window_gap          3
bspc config top_padding		20

bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config click_to_focus	true
bspc config single_monocle	false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc focus_follows_pointer	 true
bspc config focused_border_color "#0d6a6a"











####BSPWM rules########
bspc rule -a surf state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium follow=on
bspc rule -a firefox follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=tiled
bspc rule -a Sxiv state=tiled
bspc rule -a *:*:ranger state=floating rectangle=900x500+900+200
##bspc rule -a *:*:music state=floating sticky=on rectangle=900x500+900+200

